version: '3'

services: 
    testenv:
      image: backtest
      container_name: backend
      build: 
        context: .
        dockerfile: Dockerfiletest
      depends_on:
        database:
           condition: service_healthy

    database:
        image: mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: horondi
        expose:
            - 27017
        healthcheck:
          test: ["CMD", "mongo"]
          interval: 30s
          timeout: 10s
          retries: 5

